
package com.ibm.jaxws.client;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GetRandomService", targetNamespace = "http://services.jaxws.ibm.com/", wsdlLocation = "WEB-INF/wsdl/GetRandomService.wsdl")
public class GetRandomService
    extends Service
{

    private final static URL GETRANDOMSERVICE_WSDL_LOCATION;
    private final static WebServiceException GETRANDOMSERVICE_EXCEPTION;
    private final static QName GETRANDOMSERVICE_QNAME = new QName("http://services.jaxws.ibm.com/", "GetRandomService");

    static {
            GETRANDOMSERVICE_WSDL_LOCATION = com.ibm.jaxws.client.GetRandomService.class.getResource("/WEB-INF/wsdl/GetRandomService.wsdl");
        WebServiceException e = null;
        if (GETRANDOMSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'WEB-INF/wsdl/GetRandomService.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        GETRANDOMSERVICE_EXCEPTION = e;
    }

    public GetRandomService() {
        super(__getWsdlLocation(), GETRANDOMSERVICE_QNAME);
    }

    public GetRandomService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GETRANDOMSERVICE_QNAME, features);
    }

    public GetRandomService(URL wsdlLocation) {
        super(wsdlLocation, GETRANDOMSERVICE_QNAME);
    }

    public GetRandomService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GETRANDOMSERVICE_QNAME, features);
    }

    public GetRandomService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetRandomService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GetRandom
     */
    @WebEndpoint(name = "GetRandomPort")
    public GetRandom getGetRandomPort() {
        return super.getPort(new QName("http://services.jaxws.ibm.com/", "GetRandomPort"), GetRandom.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetRandom
     */
    @WebEndpoint(name = "GetRandomPort")
    public GetRandom getGetRandomPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.jaxws.ibm.com/", "GetRandomPort"), GetRandom.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GETRANDOMSERVICE_EXCEPTION!= null) {
            throw GETRANDOMSERVICE_EXCEPTION;
        }
        return GETRANDOMSERVICE_WSDL_LOCATION;
    }

}
