
package com.ibm.jaxws.client;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GetRandom", targetNamespace = "http://services.jaxws.ibm.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GetRandom {


    /**
     * 
     * @return
     *     returns com.ibm.jaxws.client.ResponseMessage
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRandom", targetNamespace = "http://services.jaxws.ibm.com/", className = "com.ibm.jaxws.client.GetRandom_Type")
    @ResponseWrapper(localName = "getRandomResponse", targetNamespace = "http://services.jaxws.ibm.com/", className = "com.ibm.jaxws.client.GetRandomResponse")
    public ResponseMessage getRandom();

}
